
package ksscinema;

import javax.swing.*;
import java.awt.*;
import java.util.Enumeration;

public class payment extends javax.swing.JFrame {
    
    private String selectedMovie;
    private String selectedDate;
    private String selectedShowtime;
    private String selectedLocation;

    public payment(String movie, String date, String showtime, String location){
        //to get data from 2 previous frames
        this.selectedMovie = movie;
        this.selectedDate = date;
        this.selectedShowtime = showtime;
        this.selectedLocation = location;
        
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("C:\\Users\\ainnuraida\\Downloads\\SEMESTER 3\\SPG 0453\\assignments\\mini project\\KSSCinema\\src\\ksscinema\\logokss.png");
        this.setIconImage(icon);
        paylogoo();
        
        setLocationRelativeTo(null); //to center the frame
        booking(movie, date, showtime, location);
        OBpay5.setEnabled(false); //to disable combo box if user didn't select anything
    }
    
    private void booking(String movie, String date, String showtime, String location){
        
        Lmname.setText(movie);
        Ldate.setText(date);
        Lshowtime.setText(showtime);
        Llocation.setText(location);
        //Lseats.setText(); //seat number
        //Ltickets.setText(location); //tickets
        //Ltotalprice.setText(); //total price
    }
    
    private void paylogoo(){
        
        int width = 50;
        int height = 30;
        
        ImageIcon pay = new ImageIcon("C:\\Users\\ainnuraida\\Downloads\\SEMESTER 3\\SPG 0453\\assignments\\mini project\\KSSCinema\\src\\ksscinema\\visa.png");
        Image scaledImage = pay.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        lp1.setIcon(scaledIcon);
        
        ImageIcon pay1 = new ImageIcon("C:\\Users\\ainnuraida\\Downloads\\SEMESTER 3\\SPG 0453\\assignments\\mini project\\KSSCinema\\src\\ksscinema\\mcard.png");
        Image scaledImage1 = pay1.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon1 = new ImageIcon(scaledImage1);
        lp2.setIcon(scaledIcon1);
        
        ImageIcon pay2 = new ImageIcon("C:\\Users\\ainnuraida\\Downloads\\SEMESTER 3\\SPG 0453\\assignments\\mini project\\KSSCinema\\src\\ksscinema\\pp.png");
        Image scaledImage2 = pay2.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon2 = new ImageIcon(scaledImage2);
        lp3.setIcon(scaledIcon2);
        
        ImageIcon pay3 = new ImageIcon("C:\\Users\\ainnuraida\\Downloads\\SEMESTER 3\\SPG 0453\\assignments\\mini project\\KSSCinema\\src\\ksscinema\\apple.png");
        Image scaledImage3 = pay3.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon3 = new ImageIcon(scaledImage3);
        lp4.setIcon(scaledIcon3);
        
        ImageIcon pay4 = new ImageIcon("C:\\Users\\ainnuraida\\Downloads\\SEMESTER 3\\SPG 0453\\assignments\\mini project\\KSSCinema\\src\\ksscinema\\tng.png");
        Image scaledImage4 = pay4.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon4 = new ImageIcon(scaledImage4);
        lp5.setIcon(scaledIcon4);
        
        ImageIcon pay5 = new ImageIcon("C:\\Users\\ainnuraida\\Downloads\\SEMESTER 3\\SPG 0453\\assignments\\mini project\\KSSCinema\\src\\ksscinema\\fpx.png");
        Image scaledImage5 = pay5.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon5 = new ImageIcon(scaledImage5);
        lp6.setIcon(scaledIcon5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpPay = new javax.swing.ButtonGroup();
        paymentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mname = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        backBtn2 = new javax.swing.JButton();
        paymentmethodLabel = new javax.swing.JLabel();
        onlinebanking = new javax.swing.JRadioButton();
        pay1 = new javax.swing.JRadioButton();
        pay2 = new javax.swing.JRadioButton();
        pay3 = new javax.swing.JRadioButton();
        pay4 = new javax.swing.JRadioButton();
        pay5 = new javax.swing.JRadioButton();
        OBpay5 = new javax.swing.JComboBox<>();
        termscond = new javax.swing.JCheckBox();
        date = new javax.swing.JLabel();
        showtime = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        Lmname = new javax.swing.JLabel();
        Llocation = new javax.swing.JLabel();
        Lshowtime = new javax.swing.JLabel();
        Ldate = new javax.swing.JLabel();
        Ltotalprice = new javax.swing.JLabel();
        seats = new javax.swing.JLabel();
        tprice = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tickets = new javax.swing.JLabel();
        Ltickets = new javax.swing.JLabel();
        Lseats = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        lp6 = new javax.swing.JLabel();
        lp3 = new javax.swing.JLabel();
        lp2 = new javax.swing.JLabel();
        lp1 = new javax.swing.JLabel();
        lp4 = new javax.swing.JLabel();
        lp5 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();

        btnGrpPay.add(pay1);
        btnGrpPay.add(pay2);
        btnGrpPay.add(pay3);
        btnGrpPay.add(pay4);
        btnGrpPay.add(pay5);
        btnGrpPay.add(onlinebanking);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment");

        paymentPanel.setBackground(new java.awt.Color(0, 0, 0));
        paymentPanel.setMaximumSize(new java.awt.Dimension(1600, 900));
        paymentPanel.setMinimumSize(new java.awt.Dimension(1600, 900));
        paymentPanel.setPreferredSize(new java.awt.Dimension(1600, 900));
        paymentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 217, 115));
        jLabel1.setText("BOOKING DETAILS");
        paymentPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, -1, -1));

        mname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mname.setForeground(new java.awt.Color(142, 217, 115));
        mname.setText("MOVIE NAME");
        paymentPanel.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, -1, -1));

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelBtn.setText("CANCEL");
        cancelBtn.setFocusPainted(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        paymentPanel.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 810, 140, 40));

        nextBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nextBtn.setText("NEXT");
        nextBtn.setFocusPainted(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        paymentPanel.add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 810, 140, 40));

        backBtn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn2.setText("BACK");
        backBtn2.setFocusPainted(false);
        paymentPanel.add(backBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 810, 140, 40));

        paymentmethodLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paymentmethodLabel.setForeground(new java.awt.Color(142, 217, 115));
        paymentmethodLabel.setText("SELECT A PAYMENT METHOD");
        paymentPanel.add(paymentmethodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        onlinebanking.setBackground(new java.awt.Color(0, 0, 0));
        onlinebanking.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        onlinebanking.setForeground(new java.awt.Color(255, 255, 255));
        onlinebanking.setText("Online Banking");
        onlinebanking.setFocusPainted(false);
        onlinebanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlinebankingActionPerformed(evt);
            }
        });
        paymentPanel.add(onlinebanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        pay1.setBackground(new java.awt.Color(0, 0, 0));
        pay1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pay1.setForeground(new java.awt.Color(255, 255, 255));
        pay1.setText("VISA");
        pay1.setFocusPainted(false);
        pay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay1ActionPerformed(evt);
            }
        });
        paymentPanel.add(pay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        pay2.setBackground(new java.awt.Color(0, 0, 0));
        pay2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pay2.setForeground(new java.awt.Color(255, 255, 255));
        pay2.setText("Master Card");
        pay2.setFocusPainted(false);
        pay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay2ActionPerformed(evt);
            }
        });
        paymentPanel.add(pay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        pay3.setBackground(new java.awt.Color(0, 0, 0));
        pay3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pay3.setForeground(new java.awt.Color(255, 255, 255));
        pay3.setText("PayPal");
        pay3.setFocusPainted(false);
        pay3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay3ActionPerformed(evt);
            }
        });
        paymentPanel.add(pay3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        pay4.setBackground(new java.awt.Color(0, 0, 0));
        pay4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pay4.setForeground(new java.awt.Color(255, 255, 255));
        pay4.setText("Apple Pay");
        pay4.setFocusPainted(false);
        pay4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay4ActionPerformed(evt);
            }
        });
        paymentPanel.add(pay4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        pay5.setBackground(new java.awt.Color(0, 0, 0));
        pay5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pay5.setForeground(new java.awt.Color(255, 255, 255));
        pay5.setText("Touch 'n Go eWallet");
        pay5.setFocusPainted(false);
        pay5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay5ActionPerformed(evt);
            }
        });
        paymentPanel.add(pay5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        OBpay5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OBpay5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bank Islam", "Maybank2U", "CIMB", "Bank Rakyat", "myBSN" }));
        OBpay5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OBpay5ActionPerformed(evt);
            }
        });
        paymentPanel.add(OBpay5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 200, -1));

        termscond.setBackground(new java.awt.Color(0, 0, 0));
        termscond.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        termscond.setForeground(new java.awt.Color(255, 255, 255));
        termscond.setText("I have read and agree to the Terms & Conditions applied.");
        termscond.setFocusPainted(false);
        paymentPanel.add(termscond, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(142, 217, 115));
        date.setText("DATE");
        paymentPanel.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 170, -1, -1));

        showtime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showtime.setForeground(new java.awt.Color(142, 217, 115));
        showtime.setText("SHOWTIME");
        paymentPanel.add(showtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 270, -1, -1));

        location.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        location.setForeground(new java.awt.Color(142, 217, 115));
        location.setText("LOCATION");
        paymentPanel.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, -1, -1));

        Lmname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lmname.setForeground(new java.awt.Color(255, 255, 255));
        Lmname.setText("name");
        paymentPanel.add(Lmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 240, -1));

        Llocation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Llocation.setForeground(new java.awt.Color(255, 255, 255));
        Llocation.setText("location");
        paymentPanel.add(Llocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, 240, -1));

        Lshowtime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lshowtime.setForeground(new java.awt.Color(255, 255, 255));
        Lshowtime.setText("showtime");
        paymentPanel.add(Lshowtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 310, 240, -1));

        Ldate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ldate.setForeground(new java.awt.Color(255, 255, 255));
        Ldate.setText("date");
        paymentPanel.add(Ldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 210, 240, -1));

        Ltotalprice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Ltotalprice.setForeground(new java.awt.Color(255, 255, 255));
        Ltotalprice.setText("price");
        paymentPanel.add(Ltotalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, 240, -1));

        seats.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seats.setForeground(new java.awt.Color(142, 217, 115));
        seats.setText("SEAT NO");
        paymentPanel.add(seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 380, -1, -1));

        tprice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tprice.setForeground(new java.awt.Color(142, 217, 115));
        tprice.setText("TOTAL PRICE");
        paymentPanel.add(tprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 510, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("______________________________________________________");
        paymentPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 100, 540, -1));

        tickets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tickets.setForeground(new java.awt.Color(142, 217, 115));
        tickets.setText("TICKETS");
        paymentPanel.add(tickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, -1, -1));

        Ltickets.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ltickets.setForeground(new java.awt.Color(255, 255, 255));
        Ltickets.setText("tickets");
        paymentPanel.add(Ltickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, 240, -1));

        Lseats.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lseats.setForeground(new java.awt.Color(255, 255, 255));
        Lseats.setText("seats");
        paymentPanel.add(Lseats, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 420, 240, -1));

        logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout.setText("[ < ]");
        logout.setToolTipText("LOGOUT");
        logout.setFocusPainted(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        paymentPanel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lp6.setForeground(new java.awt.Color(255, 255, 255));
        lp6.setText("jLabel3");
        paymentPanel.add(lp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 50, 30));

        lp3.setForeground(new java.awt.Color(255, 255, 255));
        lp3.setText("jLabel3");
        paymentPanel.add(lp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 50, 30));

        lp2.setForeground(new java.awt.Color(255, 255, 255));
        lp2.setText("jLabel3");
        paymentPanel.add(lp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 50, 30));

        lp1.setForeground(new java.awt.Color(255, 255, 255));
        lp1.setText("jLabel3");
        paymentPanel.add(lp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 50, 30));

        lp4.setForeground(new java.awt.Color(255, 255, 255));
        lp4.setText("jLabel3");
        paymentPanel.add(lp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 50, 30));

        lp5.setForeground(new java.awt.Color(255, 255, 255));
        lp5.setText("jLabel3");
        paymentPanel.add(lp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 50, 30));

        username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("username");
        paymentPanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 185, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Booking has been cancelled. Returning to the Home Page.", "Booking Cancelled", JOptionPane.INFORMATION_MESSAGE);
        this.dispose(); //close this frame
        homepage hp = new homepage(); //go back to home page
        hp.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        //get selected payment method
        String selectedPayment = null;
        
        for (Enumeration<AbstractButton> buttons = btnGrpPay.getElements(); buttons.hasMoreElements();){
            AbstractButton button = buttons.nextElement();
            
            if (button.isSelected()) {
                if (button == onlinebanking){
                    selectedPayment = (String) OBpay5.getSelectedItem();
                } else {
                    selectedPayment = button.getText();
                }
            }
        }
        
        //System.out.println("Payment: " + selectedPayment);
        boolean tc = termscond.isSelected();

        if (selectedPayment == null && !tc) { // if neither payment method nor T&C is selected
            JOptionPane.showMessageDialog(this, "Please fill out all the fields.", "Selection Required", JOptionPane.ERROR_MESSAGE);
            
        } else if (selectedPayment != null && !tc) { // if payment method is selected but T&C is not checked
            JOptionPane.showMessageDialog(this, "Please read and agree to the T&C applied.", "Terms & Condition", JOptionPane.ERROR_MESSAGE);
            
        } else if (selectedPayment == null && tc) { // if T&C is checked but no payment method is selected
            JOptionPane.showMessageDialog(this, "Please fill out all the fields.", "Selection Required", JOptionPane.ERROR_MESSAGE);
            
        } else {
            // if all fields are filled
            this.dispose();
            details d = new details(selectedMovie, selectedDate, selectedShowtime, selectedLocation, selectedPayment);
            d.setVisible(true);
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void onlinebankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlinebankingActionPerformed
        OBpay5.setEnabled(true); //enable combo box only when this button is selected
    }//GEN-LAST:event_onlinebankingActionPerformed

    private void pay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay1ActionPerformed
        OBpay5.setEnabled(false); //disable combo box (online banking) 
    }//GEN-LAST:event_pay1ActionPerformed

    private void pay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay2ActionPerformed
        OBpay5.setEnabled(false); //disable combo box (online banking) 
    }//GEN-LAST:event_pay2ActionPerformed

    private void pay3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay3ActionPerformed
        OBpay5.setEnabled(false); //disable combo box (online banking) 
    }//GEN-LAST:event_pay3ActionPerformed

    private void pay4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay4ActionPerformed
        OBpay5.setEnabled(false); //disable combo box (online banking) 
    }//GEN-LAST:event_pay4ActionPerformed

    private void pay5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay5ActionPerformed
        OBpay5.setEnabled(false); //disable combo box (online banking) 
    }//GEN-LAST:event_pay5ActionPerformed

    private void OBpay5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OBpay5ActionPerformed
        
    }//GEN-LAST:event_OBpay5ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.dispose(); //this: component; syntax to close this frame when user click logout button
        KSSCinema login = new KSSCinema(); // go to login/signup page
        login.frame.setVisible(true); //make the login frame visible
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment("", "", "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ldate;
    private javax.swing.JLabel Llocation;
    private javax.swing.JLabel Lmname;
    private javax.swing.JLabel Lseats;
    private javax.swing.JLabel Lshowtime;
    private javax.swing.JLabel Ltickets;
    private javax.swing.JLabel Ltotalprice;
    private javax.swing.JComboBox<String> OBpay5;
    private javax.swing.JButton backBtn2;
    private javax.swing.ButtonGroup btnGrpPay;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel location;
    private javax.swing.JButton logout;
    private javax.swing.JLabel lp1;
    private javax.swing.JLabel lp2;
    private javax.swing.JLabel lp3;
    private javax.swing.JLabel lp4;
    private javax.swing.JLabel lp5;
    private javax.swing.JLabel lp6;
    private javax.swing.JLabel mname;
    private javax.swing.JButton nextBtn;
    private javax.swing.JRadioButton onlinebanking;
    private javax.swing.JRadioButton pay1;
    private javax.swing.JRadioButton pay2;
    private javax.swing.JRadioButton pay3;
    private javax.swing.JRadioButton pay4;
    private javax.swing.JRadioButton pay5;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel paymentmethodLabel;
    private javax.swing.JLabel seats;
    private javax.swing.JLabel showtime;
    private javax.swing.JCheckBox termscond;
    private javax.swing.JLabel tickets;
    private javax.swing.JLabel tprice;
    public javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}